version: "3.9"

services:
  mynginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mynginx
    ports:
      - "8080:8080"
    volumes:
      - ./html:/var/www/html:ro
    restart: unless-stopped